on: 
    push:
      branches:
      - master
name: Deploy to Demo Site
jobs:
  deployToDemo:
    name: Deploy to Demo Site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set Up Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.15'
    - run: npm run-script build-prod
    - name: Build Failure
      if: failure()
      uses: Ilshidur/action-slack@2a8ddb6db23f71a413f9958ae75bbc32bbaa6385
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: ":warning: Failed to build project :warning:"
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - run: aws s3 cp /home/runner/work/LIQWIDS/LIQWIDS/dist/ s3://test.wim.usgs.gov/liqwids/ --recursive
    - name: AWS Failure
      if: failure()
      uses: Ilshidur/action-slack@2a8ddb6db23f71a413f9958ae75bbc32bbaa6385
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: ":warning: Failed to deploy to demo site :warning:"
    - name: GitHub Action for Slack
      uses: Ilshidur/action-slack@9273a03
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: ":success: Successfully deployed to test.wim.usgs.gov/liqwids/"
  